# Unique project identifier
sonar.projectKey=chai-code-microservices
sonar.projectName=Chai Code Microservices
sonar.projectVersion=1.0.0

# Path to the source directories relative to the root
sonar.sources=services/api-gateway,services/auth-service/src,services/chatbot-service/src,services/course-service/src

# Exclude third-party code and configurations from analysis
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.test.js, **/*.spec.js, services/auth-service/src/config/**, services/course-service/src/config/**

# Files to exclude from coverage calculations (but still scan for bugs/vulnerabilities)
sonar.coverage.exclusions=**/*.controller.js, **/*.routes.js, **/*.validation.js, **/config/**, **/server.js, **/app.js, services/api-gateway/**, services/chatbot-service/**, services/auth-service/src/modules/routes.js, services/course-service/src/modules/routes.js, services/auth-service/src/modules/utils/**, services/course-service/src/modules/utils/**, services/auth-service/src/modules/middleware/**, services/course-service/src/modules/payments/payment.service.js, services/auth-service/src/modules/users/**, services/course-service/src/modules/progress/**, **/error.middleware.js, **/validate.middleware.js, services/auth-service/src/modules/enrollments/**, services/auth-service/src/modules/progress/**, **/*prisma*

# Test files to run and analyze for coverage
sonar.tests=services/auth-service/src,services/course-service/src
sonar.test.inclusions=**/*.test.js, **/*.spec.js

# Path to the LCOV coverage report generated by Vitest (or your test runner)
sonar.javascript.lcov.reportPaths=services/auth-service/coverage/lcov.info,services/course-service/coverage/lcov.info

# Source code encoding
sonar.sourceEncoding=UTF-8

# Project access token
sonar.login=sqp_0edaae8404116628dbc30acfc31ae96baf379066

# Host URL for local SonarQube
sonar.host.url=http://localhost:9000
